# Generated by Django 5.2 on 2025-06-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentos',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.estados'),
            preserve_default=False,
        ),
    ]
